version: '3.7'

services:
  app:
    build: app/
    restart: always
    networks:
      - backend

  proxy:
    build: proxy/
    ports:
      - 80:80
    restart: always
    depends_on:
      - app
    networks:
      - backend
      - proxy

networks:
  backend:
  proxy:
